### DISCUSSION TITLE
MariaDB support

### DISCUSSION THREAD

**Discussion by wickham-c** [damms005/devdb-vscode#45] [Ideas]
Thanks for contributing this VS Code extension; it certainly looks very promising. How easy would it be to auto-detect `DB_HOST=mariadb` from the .env file so as to provide support for MariaDB?

**Comment by damms005** [comment]
Thank you!

This is actually surprisingly easy to support MariaDB. I think I should write a short guide at this point being the second time I am asked this question haha.

Check my comment here if you want to give a stab at it and submit a PR so we look at it together: https://github.com/damms005/devdb-vscode/discussions/38#discussioncomment-8158862

You can also ask follow up questions here if needed

Thanks again.

**Comment by damms005** [comment]
@cmwickham-pse2 I decided to implement this.

Although you mentioned `DB_HOST=mariadb` but I believe you meant `DB_CONNECTION=mariadb`, because Laravel Sail does not currently ship with support for MariaDB.

So, for MariaDB, simply use `DB_CONNECTION=mysql` in your `.env` file. This follows Laravel convention.

If instead you are using [`.devdbrc` config file](https://github.com/damms005/devdb-vscode/blob/main/README.md#2-config-based-database-loading), simply create an entry similar to [a MySQL entry](https://github.com/damms005/devdb-vscode/blob/main/README.md#mysql-database-configuration-file-example).

**Reply by wickham-c** [reply]
Thanks for your reply Damilola. 

Laravel Sail does support MariaDB (see [this build script](https://laravel.build/example-app?with=mariadb&devcontainer)): the generated `docker-compose.yml` file references a `mariadb:10` container image:
```
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
```

The generated `.env` file includes the following variables:
```
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_POST=3306
DB_DATABASE=projectname
DB_USERNAME=sail
DB_PASSWORD=password
```

Unfortunately, DevDB only seems to offer me a "SQLite Database File Picker" option and nothing specific to MySQL/MariaDB, so I'm guessing zero-config is tripping up on something.

I've also tried creating a `.devdbrc` file in my project root, containing the following:
```
[
  {
    "name": "My MariaDB database", // <-- to identify the connection
    "type": "mysql", // <- or "mariadb" if you are using MariaDB
    "host": "mariadb",
    "port": "3306",
    "username": "sail",
    "password": "password",
    "database": "projectname" // <-- the database to show in VS Code DevDb view
  }
]
```
...and have tried the `"type": "mariadb",` variation, but still only see the "SQLite Database File Picker" option.

Am I doing something obviously wrong?
