### ISSUE TITLE
DevDB Fails to connect to db

### ISSUE THREAD

**Issue by AcaroMan** [damms005/devdb-vscode#103]
### Extension Version

v2.5.1

### OS and Version

WSL: 2.4.13.0 ;kernel: 5.15.167.4-1 ;WSLg: 1.0.65 ;MSRDC: 1.2.5716 ;Direct3D: 1.611.1-81528511 ;DXCore: 10.0.26100.1-240331-1435.ge-release ;Windows: 10.0.26100.3624

### VS Code Version

v1.92.0-insider

### Database name and Version

mysql  Ver 8.0.36 for Linux on x86_64 (MySQL Community Server - GPL)

### Steps to reproduce

Launch VSCode on Windows, with ssh connection to the WSL.
1. Exensions boots currectly and logs as seen in the Screenshots "section"
Tried the following ways
2.1 When using simply the .env in the Laravel source code (which is inside the WSL)
2.2 Creating a .devdbrc with the following content:
```
[
	{
		"name": "My test MySQL database",
		"type": "mysql",
		"host": "127.0.0.1" // also tried with "mysql" (docker name),
		"port": "3306",
		"username": "*******",
		"password": "*******",
		"database": "******" // <-- the database to show in VS Code DevDb view
	},
]
```

As shown in the logs, only SQLite Database File Picker  is available on the GUI

### Expected behavior

DevDB working with containerized Laravel mysql

### Screenshots

DevDB logs:
[Init] Getting available providers... 
[Init] Checking provider: Laravel Local SQLite (default) 
[Init] Checking provider: SQLite Database File Picker 
[Init] Checking provider: Config File 
[Init] Checking provider: Laravel Mysql (with Sail support) 
[Laravel MySQL] Checking if Laravel MySQL provider can be used in the current workspace... 
[Laravel env file parser] Fetching connection details from .env file. Laravel connection:  mysql
[Init] Checking provider: Laravel PostgreSQL 
[Laravel env file parser] Fetching connection details from .env file. Laravel connection:  pgsql
[Init] Checking provider: DDEV - MySQL 
[Postgres DDEV] Not a DDEV project
[Init] Checking provider: DDEV - PostgreSQL 
[Postgres DDEV] Not a DDEV project
[Init] Checking provider: Adonis MySQL (Lucid ORM) 
[Adonis PostgreSQL] No Adonis database config file found 
[MySQL AdonisJS] Not an AdonisJS project
[Init] Checking provider: Adonis PostgreSQL (Lucid ORM) 
[Adonis PostgreSQL] No Adonis database config file found 
[Postgres AdonisJS] Not an AdonisJS project
[Init] Laravel Local SQLite (default) useable in workspace: no 
[Init] SQLite Database File Picker useable in workspace: yes 
[Init] DDEV - MySQL useable in workspace: no 
[Init] DDEV - PostgreSQL useable in workspace: no 
[Init] Adonis MySQL (Lucid ORM) useable in workspace: no 
[Init] Adonis PostgreSQL (Lucid ORM) useable in workspace: no 
[Init] Config File useable in workspace: no 
[Laravel env file parser] Laravel/mysql2 connection details: connection=mysql, host=mysql, username=root, database=portal_gestao_prod 
[Laravel env file parser] Laravel/postgres connection details: connection=mysql, host=mysql, username=root, database=portal_gestao_prod 
[Laravel env file parser] Connection type mismatch: expected "pgsql", found "mysql" 
[Init] Laravel PostgreSQL useable in workspace: no 
[Laravel env file parser] Laravel/mysql2 connection details: mysql mysql 3306 root portal_gestao_prod
[Connector - Laravel provider - env file parser] Attempting to connect to database: dialect=mysql2, host=mysql, port=3306, username=root, database=portal_gestao_prod 
[Laravel MySQL] Connection status: successful 
[Laravel MySQL] Creating MySQL engine... 
[Laravel MySQL] OK 
[Init] error: Laravel Mysql (with Sail support) - Error: connect ETIMEDOUT 
[Init] Available providers: SQLite Database File Picker 

![Image](https://github.com/user-attachments/assets/d7ede5fc-89bd-4dfc-8489-af21cb5d56fb)

![Image](https://github.com/user-attachments/assets/e1949f21-e691-4012-a33a-a472aa910368)
.env

![Image](https://github.com/user-attachments/assets/437957b1-eaa1-4711-baca-46d97921e560)

### Additional context

Host Windows Machine with WSL inside
WSL running docker with different containers for mysql, nginx and Laravel.
mysql 3306 is open to Windows host
Not using Laravel Sail

**Comment by grika335** [comment]
Orange

**Comment by AcaroMan** [comment]
WSL:
On Windows search for "Windows Features" and select the following: Virtual Machine Platform; Windows Subsystem for Linux.
reboot windows
set wsl to version 2 with `wsl --set-default-version 2` (PowerShell)
Install Ubuntu from Windows store and run afterwards on PS
```
wsl --update
wsl --set-version Ubuntu 2
```

Inside WSL install Docker
(I ran the following commands but some of them might not be necessary)

```
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo usermod -aG docker $USER
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
```
Reboot WSL: `wsl.exe -t Ubuntu` and then `wsl.exe -d Ubuntu`

Docker should be running.

Again, some of the following steps might be oddly specific due to my current environment

Inside WSL create the folders `git\laravelapp `and `docker` (might have to `chown` the git folder)

Inside the docker folder add the following `docker-compose.yml`

```
networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24  
        
x-extra-hosts: &default-extra-hosts
  - "laravelapp.test:172.18.0.2"

services:
# Nginx Service
  nginx:
    container_name: nginx
    image: nginx:stable-bookworm-perl
    restart: unless-stopped
    volumes:
      - /git:/var/www
      - /docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - /docker/nginx/ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
        ipv4_address: 172.18.0.2
        
# Databases
  mysql:
    container_name: mysql
    image: mysql:8.0.36-bookworm
    restart: unless-stopped
    ports:
      - 3306:3306
    depends_on:
      - nginx
    volumes:
      - /docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=root
    networks:
      internal:
        ipv4_address: 172.18.0.3
    extra_hosts: *default-extra-hosts

  laravelapp:
    container_name: laravelapp
    build:
      context: .
      dockerfile: laravelapp_dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/laravelapp
    volumes:
      - /git:/var/www
    ports:
      - 5173:5173
    networks:
      internal:
        ipv4_address: 172.18.0.4
    extra_hosts: *default-extra-hosts
```
and the following `laravelapp_dockerfile`

```
FROM php:8.3.7-fpm-bookworm

ENV ACCEPT_EULA=Y
ENV COMPOSER_VERSION=2.7.4
ENV NODE_VERSION=20

# Fix Project Folder Permissions
RUN chown -R www-data:www-data /var/www

# Update Base Image Packages
RUN apt update && apt upgrade -y

# Install necessary base packages for the project
RUN apt update && apt install -y bash gnupg libpng-dev libzip-dev unzip git rsync

# Install Node.JS and NPM
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - &&\
apt-get install -y nodejs

# Retrieve the script used to install PHP extensions from the source container.
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/install-php-extensions

# Install required PHP extensions and all their prerequisites available.
RUN chmod uga+x /usr/bin/install-php-extensions \
    && sync \
    && install-php-extensions bcmath ds exif gd intl opcache pcntl redis zip pdo_mysql mysqli pdo xml soap

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION}

# Install System Fonts
RUN apt update && apt install -y fonts-liberation2

# Tweaked PHP Settings
COPY docker-php-tweaks.ini /usr/local/etc/php/conf.d/docker-php-tweaks.ini

# Cleanup
RUN apt autoremove && apt autoclean

# Switch to NGINX www-data user context and sync GUID with Host Machine
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

USER www-data
```

```
(not necessary but)On windows `System32\drivers\etc\hosts` insert
127.0.0.1		laravelapp.test
```

Inside `git/laravelapp` insert a Laravel app

Inside the docker folder build the app container `docker compose build laravelapp`
and boot them up `docker compose up -d`

Now for VScode (installed on windows)
You need at least the following extension (other than yours)
WSL (ms-vscode-remote.remote-wsl)
Docker (ms-azuretools.vscode-docker)

Now on vscode on the bottom left you should be able to connect to WSL

![Image](https://github.com/user-attachments/assets/7d83c087-1c52-4f01-a088-98ddfec72df3)
![Image](https://github.com/user-attachments/assets/8023fdbf-442b-4be5-841a-5d376db133db)

And after switching to the WSL it should show on the docker extension tab the necessary containers running
On my personal setup i have some extra running that should not interefere with the setup

Afterwards i scope vscode to the `git/laravelapp` folder and thats my setup

I believe thats all the necessary settings/configurations you would need to have a similar setup.
I had to tweak some of the settings i provided due to privacy reasons, but i believe it should work

Now for LaravelExtraIntellisense.phpCommand i need the following setting for it to work
`/git/laravelapp/php_executable -r "{code}"`

and the php_executable has the following code
```
#!/bin/sh
docker exec -t laravelapp php "$@"
```
I've also tried using this setting for your extension, but it didn't seem to help

Hope this can help and thanks for your attention
