### ISSUE TITLE
.devdbrc does not override laravel .env config

### ISSUE THREAD

**Issue by spinanicky** [damms005/devdb-vscode#104]
### Extension Version

2.5.4

### OS and Version

Windows - running docker with Ubuntu WSL

### VS Code Version

v1.99.2

### Database name and Version

mariadb

### Steps to reproduce

1. launch vs code in a laravel sail project (on windows with WSL)
2. add a .devdbrc file into the root of the project folder
3. run mariadb on a custom network and port in docker-compose.yml (forward db port is set to 3307)
```
front-mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            sail: null
            cust-network:
                aliases:
                    - front-db
```
5. Connections don't show up

### Expected behavior

Connections should appear

### Screenshots

![Image](https://github.com/user-attachments/assets/6bf45e81-2999-4498-b290-fb7255beab52)
